const { invoke } = window.__TAURI__.core;
const { isPermissionGranted, requestPermission, sendNotification } = window.__TAURI__.notification;
let currentDate = ""; let isPinned = false; let currentTheme = "light"; let edgeHide = "none"; let compactMode = false;
const themes = { light: { bg: "#F8FAFC", card: "#FFFFFF", text: "#1E293B", border: "#E2E8F0", primary: "#2563EB" }, dark: { bg: "#1E1E1E", card: "#2D2D2D", text: "#E0E0E0", border: "#404040", primary: "#4A90D9" }, highContrast: { bg: "#000000", card: "#000000", text: "#FFFFFF", border: "#FFFFFF", primary: "#FFFF00" }, sepia: { bg: "#F4ECD8", card: "#FAF3E0", text: "#5B4636", border: "#D4C4A8", primary: "#8B4513" } };
async function init() { currentDate = await invoke("get_today"); document.getElementById("currentDate").textContent = "今日日期: " + currentDate; await loadTasks(); setupEventListeners(); startTaskCheck(); applyTheme(currentTheme); }
async function loadTasks() { try { const tasks = await invoke("get_tasks", { date: currentDate }); renderTasks(tasks); } catch (e) { console.error(e); } }
function applyTheme(theme) { var t = themes[theme] || themes.light; document.body.style.background = t.bg; document.querySelectorAll(".task-item, .modal-content, .date-display").forEach(function(el) { el.style.background = t.card; el.style.borderColor = t.border; }); document.body.style.color = t.text; document.querySelectorAll(".add-btn, .save-btn").forEach(function(el) { el.style.background = t.primary; }); }
function renderTasks(tasks) { var taskList = document.getElementById('taskList'); if (tasks.length === 0) { taskList.innerHTML = '<div class="empty-state"><p>暂无任务</p></div>'; return; } var incomplete = tasks.filter(function(t) { return !t.completed; }).sort(function(a,b) { return a.time.localeCompare(b.time); }); var completed = tasks.filter(function(t) { return t.completed; }).sort(function(a,b) { return a.time.localeCompare(b.time); }); var sorted = incomplete.concat(completed); var now = new Date().toTimeString().slice(0,5); taskList.innerHTML = ''; sorted.forEach(function(t) { var od = !t.completed && t.time <= now; var div = document.createElement('div'); div.className = 'task-item ' + (t.completed ? 'completed' : '') + ' ' + (od ? 'overdue' : ''); div.setAttribute('data-id', t.id); if (compactMode) { div.innerHTML = '<div class="task-checkbox ' + (t.completed ? 'checked' : '') + '"></div><div class="task-content compact"><div class="task-title"></div><div class="task-time"></div></div>'; } else { div.innerHTML = '<div class="task-checkbox ' + (t.completed ? 'checked' : '') + '"></div><div class="task-content"><div class="task-title"></div><div class="task-time"></div></div><button class="delete-btn">X</button>'; } div.querySelector('.task-title').textContent = t.title; div.querySelector('.task-time').textContent = t.time; div.querySelector('.task-checkbox').onclick = function() { toggleTask(t.id); }; if (!compactMode) div.querySelector('.delete-btn').onclick = function() { deleteTask(t.id); }; taskList.appendChild(div); }); }
async function toggleTask(id) { try { await invoke("toggle_task",{id}); await loadTasks(); } catch(e) { console.error(e); } }
async function deleteTask(id) { try { await invoke("delete_task",{id}); await loadTasks(); } catch(e) { console.error(e); } }
function setupEventListeners() { document.getElementById('addTaskBtn').onclick = function() { document.getElementById('addModal').classList.add('show'); }; document.getElementById('closeModal').onclick = function() { document.getElementById('addModal').classList.remove('show'); }; document.getElementById('saveTaskBtn').onclick = async function() { var title = document.getElementById('taskTitle').value.trim(); var time = document.getElementById('taskTime').value; if(!title||!time) return alert('请填写'); await invoke('add_task',{title,time}); document.getElementById('addModal').classList.remove('show'); document.getElementById('taskTitle').value = ''; document.getElementById('taskTime').value = '12:00'; await loadTasks(); }; document.getElementById('pinBtn').onclick = async function() { isPinned = !isPinned; await invoke('set_always_on_top',{onTop:isPinned}); document.getElementById('pinBtn').classList.toggle('active',isPinned); if (isPinned) { compactMode = true; await invoke('set_window_size',{width:300, height:350}); document.getElementById('headerExtra').style.display = 'none'; document.getElementById('footer').style.display = 'none'; document.getElementById('addTaskBtn').style.display = 'none'; document.querySelector('.date-display').style.display = 'none'; } else { compactMode = false; await invoke('set_window_size',{width:420, height:600}); document.getElementById('headerExtra').style.display = 'flex'; document.getElementById('footer').style.display = 'block'; document.getElementById('addTaskBtn').style.display = 'flex'; document.querySelector('.date-display').style.display = 'block'; } var tasks = await invoke('get_tasks', { date: currentDate }); renderTasks(tasks); }; document.getElementById('themeBtn').onclick = function() { var themeKeys = Object.keys(themes); var idx = themeKeys.indexOf(currentTheme); currentTheme = themeKeys[(idx + 1) % themeKeys.length]; applyTheme(currentTheme); }; document.getElementById('edgeBtn').onclick = async function() { var edges = ['none', 'left', 'right', 'top']; var idx = edges.indexOf(edgeHide); edgeHide = edges[(idx + 1) % edges.length]; document.getElementById('edgeBtn').textContent = edgeHide === 'none' ? '⊞' : (edgeHide === 'left' ? '◧' : edgeHide === 'right' ? '◨' : '⧉'); if (edgeHide !== 'none') { await invoke('hide_to_edge',{edge:edgeHide}); } else { await invoke('set_window_size',{width:420, height:600}); } }; document.getElementById('historyBtn').onclick = async function() { await loadHistory(); document.getElementById('historyModal').classList.add('show'); }; document.getElementById('closeHistory').onclick = function() { document.getElementById('historyModal').classList.remove('show'); }; }
async function loadHistory() { var dates = await invoke("get_history_dates"); var h = document.getElementById("historyList"); if(!dates.length) { h.innerHTML="<div>无历史</div>"; return; } h.innerHTML = ""; for(var i=0; i<dates.length; i++) { var d = dates[i]; var pc = await invoke("get_date_stats",{date:d}); var div = document.createElement("div"); div.className = "history-item"; div.onclick = function() { viewDateTasks(d); }; div.innerHTML = "<span>"+d+"</span><span>"+pc[0]+"/"+pc[1]+"</span>"; h.appendChild(div); } }
async function viewDateTasks(date) { var tasks = await invoke("get_tasks",{date}); var h = document.getElementById("historyList"); var i = tasks.filter(function(t){return !t.completed;}); var c = tasks.filter(function(t){return t.completed;}); h.innerHTML = "<div>"+date+"</div>"; if(i.length) { var hd = document.createElement("div"); hd.style.padding = "8px 12px"; hd.style.color = "#64748B"; hd.textContent = "未完成"; h.appendChild(hd); i.forEach(function(t) { var div = document.createElement("div"); div.className = "history-item"; div.style.background = "#FEF2F2"; div.innerHTML = "<span style=\"color:#EF4444\">"+t.title+"</span><span>"+t.time+"</span>"; h.appendChild(div); }); } if(c.length) { var hd = document.createElement("div"); hd.style.padding = "8px 12px"; hd.style.color = "#64748B"; hd.textContent = "已完成"; h.appendChild(hd); c.forEach(function(t) { var div = document.createElement("div"); div.className = "history-item"; div.style.background = "#F0FDF4"; div.innerHTML = "<span style=\"text-decoration:line-through;color:#94A3B8\">"+t.title+"</span><span>"+t.time+"</span>"; h.appendChild(div); }); } }
async function showNotification(task) { try { var granted = await isPermissionGranted(); if (!granted) { var permission = await requestPermission(); granted = permission === "granted"; } if (granted) { sendNotification({ title: "任务提醒", body: "\"" + task.title + "\" 已到截止时间，请尽快完成！" }); } } catch(e) { console.error("通知错误:", e); } }
function startTaskCheck() { checkOverdueTasks(); setInterval(checkOverdueTasks, 60000); }
async function checkOverdueTasks() { try { var ot = await invoke("check_overdue_tasks"); for(var i=0; i<ot.length; i++) { var t = ot[i]; console.log("超时任务:", t.title); await showNotification(t); } await loadTasks(); } catch(e) { console.error("检查超时任务错误:", e); } }
window.toggleTask = toggleTask; window.deleteTask = deleteTask; window.loadHistory = loadHistory; window.viewDateTasks = viewDateTasks; init();
